import '../models/interaction_models.dart';
import '../psychology/emotional_state.dart';

/// Service for analyzing relational health and patterns.
///
/// Distilled from the project's advanced psychological engines.
class RelationalAnalyticsService {
  /// Analyzes long-term relational patterns from interactions.
  Future<RelationalReport> analyzeRelationalHealth(
    List<UserInteraction> interactions,
  ) async {
    if (interactions.isEmpty) {
      return const RelationalReport(
        stability: 0.5,
        engagementVelocity: 0.0,
        dominantSentiment: EmotionType.neutral,
        insights: ['Not enough data to generate insights.'],
      );
    }

    final stability = _calculateStability(interactions);
    final velocity = _calculateEngagementVelocity(interactions);
    final sentiment = _calculateDominantSentiment(interactions);
    final insights = _generateInsights(stability, velocity, sentiment);

    return RelationalReport(
      stability: stability,
      engagementVelocity: velocity,
      dominantSentiment: sentiment,
      insights: insights,
    );
  }

  double _calculateStability(List<UserInteraction> interactions) {
    if (interactions.length < 2) return 0.5;

    // Calculate variance in emotional responses
    final responses = interactions
        .where((i) => i.emotionalResponse != null)
        .map((i) => i.emotionalResponse!)
        .toList();

    if (responses.isEmpty) return 0.5;

    final uniqueResponses = responses.toSet().length;
    // Normalized stability: 1.0 if all responses are same,
    // 0.0 if all are unique.
    if (interactions.length <= 1) return 1.0;

    final stabilityScore =
        1.0 - ((uniqueResponses - 1) / (interactions.length - 1));

    return stabilityScore.clamp(0.0, 1.0);
  }

  double _calculateEngagementVelocity(List<UserInteraction> interactions) {
    if (interactions.length < 2) return 0.0;

    // Sort by timestamp
    final sorted = List<UserInteraction>.from(interactions)
      ..sort((a, b) => a.timestamp.compareTo(b.timestamp));

    final first = sorted.first.timestamp;
    final last = sorted.last.timestamp;
    final totalDays = last.difference(first).inDays;

    if (totalDays == 0) return interactions.length.toDouble();

    return interactions.length / totalDays;
  }

  EmotionType _calculateDominantSentiment(List<UserInteraction> interactions) {
    final sentimentCounts = <EmotionType, int>{};
    for (final interaction in interactions) {
      if (interaction.emotionalResponse != null) {
        final emotion = interaction.emotionalResponse!;
        sentimentCounts[emotion] = (sentimentCounts[emotion] ?? 0) + 1;
      }
    }

    if (sentimentCounts.isEmpty) return EmotionType.neutral;

    return sentimentCounts.entries
        .reduce((a, b) => a.value > b.value ? a : b)
        .key;
  }

  List<String> _generateInsights(
    double stability,
    double velocity,
    EmotionType sentiment,
  ) {
    final insights = <String>[];

    if (stability > 0.8) {
      insights.add('العلاقة تبدو مستقرة جداً وثابتة عاطفياً.');
    } else if (stability < 0.3) {
      insights.add('هناك تذبذب عاطفي ملحوظ، قد يحتاج الأمر لمساحة من الهدوء.');
    }

    if (velocity > 5.0) {
      insights.add('كثافة التفاعل عالية جداً، استمري في هذا التواصل الرائع.');
    } else if (velocity < 1.0) {
      insights.add('التفاعل يبدو هادئاً، ربما حان الوقت لمشاركة ذكرى جديدة.');
    }

    if (sentiment == EmotionType.joy || sentiment == EmotionType.calm) {
      insights.add('المناخ العام يغلب عليه السكينة والبهجة.');
    } else if (sentiment == EmotionType.sad) {
      insights.add('هناك مسحة من الشجن، الرفيق متاح دائماً للاستماع.');
    }

    return insights;
  }
}

/// A report generated by the [RelationalAnalyticsService].
class RelationalReport {
  /// Creates a [RelationalReport].
  const RelationalReport({
    required this.stability,
    required this.engagementVelocity,
    required this.dominantSentiment,
    required this.insights,
  });

  /// Stability score (0.0 - 1.0).
  final double stability;

  /// Interactions per day.
  final double engagementVelocity;

  /// Most frequent emotional state.
  final EmotionType dominantSentiment;

  /// Qualitative insights based on data.
  final List<String> insights;
}
