import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

part 'app_database.g.dart';

/// [Memories] table stores the core marital moments.
class Memories extends Table {
  /// Primary key for memories.
  IntColumn get id => integer().autoIncrement()();

  /// Title of the memory.
  TextColumn get title => text().withLength(min: 1, max: 255)();

  /// Optional description.
  TextColumn get description => text().nullable()();

  /// Encrypted content using AES-256.
  TextColumn get encryptedContent => text()(); // AES-256 encrypted content
  /// Creation timestamp.
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Path to local encrypted media file.
  TextColumn get mediaPath =>
      text().nullable()(); // Path to local encrypted file

  /// Sentiment analysis result (1-100).
  IntColumn get emotionalScore =>
      integer().nullable()(); // Sentiment analysis result

  /// Number of times viewed.
  IntColumn get viewCount => integer().withDefault(const Constant(0))();

  /// Associated hex color.
  TextColumn get color => text().nullable()();
}

/// [Reflections] table stores spiritual insights linked to memories.
class Reflections extends Table {
  /// Primary key for reflections.
  IntColumn get id => integer().autoIncrement()();

  /// Foreign key to [Memories].
  IntColumn get memoryId => integer().references(Memories, #id)();

  /// Quranic reference citation.
  TextColumn get ayahReference => text().nullable()();

  /// Hadith reference citation.
  TextColumn get hadithReference => text().nullable()();

  /// AI-generated spiritual insight.
  TextColumn get aiInsight => text()(); // Insight generated by رفيق الروح
  /// Timestamp of reflection.
  DateTimeColumn get reflectedAt =>
      dateTime().withDefault(currentDateAndTime)();
}

/// [SentMessages] table stores encrypted history of love messages.
class SentMessages extends Table {
  /// Primary key for sent messages.
  IntColumn get id => integer().autoIncrement()();

  /// Encrypted content of the message.
  TextColumn get encryptedContent => text()();

  /// Type of message (morning, evening, etc.).
  TextColumn get type => text()();

  /// Recipient identifier.
  TextColumn get recipientId => text().nullable()();

  /// Timestamp of sending.
  DateTimeColumn get sentAt => dateTime().withDefault(currentDateAndTime)();
}

/// [Surprises] table tracks spontaneous growth events.
class Surprises extends Table {
  /// Primary key for surprises.
  IntColumn get id => integer().autoIncrement()();

  /// Type of surprise (serendipity, growth, transformation).
  TextColumn get type => text()();

  /// Encrypted message content.
  TextColumn get encryptedContent => text()();

  /// Status of the surprise (dismissed, acted_upon, etc.).
  TextColumn get status => text().withDefault(const Constant('pending'))();

  /// Timestamp of creation.
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

@DriftDatabase(tables: [Memories, Reflections, SentMessages, Surprises])

/// [AppDatabase] defines the drift database and its tables.
class AppDatabase extends _$AppDatabase {
  /// The main  /// Creates an [AppDatabase].
  AppDatabase() : super(_openConnection());

  /// Creates an [AppDatabase] for testing with a specific executor.
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onUpgrade: (m, from, to) async {
          if (from < 3) {
            await m.createTable(sentMessages);
            await m.createTable(surprises);
          }
        },
      );

  /// Permanently removes all user-generated records from local persistence.
  ///
  /// Child rows are removed before their parent memories to preserve foreign
  /// key integrity. SQLite secure-delete and vacuum are applied after the
  /// transaction so that deleted payloads do not remain in free database
  /// pages.
  Future<void> clearAllSensitiveData() async {
    await customStatement('PRAGMA secure_delete = ON;');

    await transaction(() async {
      await delete(reflections).go();
      await delete(memories).go();
      await delete(sentMessages).go();
      await delete(surprises).go();
    });

    await customStatement('VACUUM;');
  }
}

LazyDatabase _openConnection() => LazyDatabase(() async {
      final dbFolder = await getApplicationDocumentsDirectory();
      final file = File(p.join(dbFolder.path, 'wing_of_nostalgia.sqlite'));
      return NativeDatabase(file);
    });
